<h1>11 conceitos Python para iniciantes em Python</h1>

Python é uma linguagem de programação que vem ganhando comunidades por todos os cantos do mundo. Muito dessa popularidade se deve por sua simplicidade e praticidade. Aprender a programar é importante para automatizar coisas chatas e termos mais tempo para coisas que nos deixam feliz.

<img src="code.jpg" width="400px">

<footnote>Photo by Hitesh Choudhary on Unsplash</footnote>

Neste post passaremos por vários conceitos importantes da linguagem Python. O texto é voltado para iniciantes, portanto começaremos com a instalação do Python no seu computador. Este post está divido nas seguintes partes:

<ul>
    <li>Preparando seu computador</li>
    <li>1. Strings</li>
    <li>2. Variáveis</li>
    <li>3. Built-in functions</li>
    <li>4. Tipos de variáveis</li>
    <li>5. Descobrindo e usando métodos</li>
    <li>6. Operando objetos</li>
    <li>7. Fatiando objetos</li>
    <li>8. If ... Else ...</li>
    <li>9. Loop For</li>
    <li>10. Funções</li>
    <li>11. Bibliotecas</li>
</ul>        

<h3>Preparando seu computador</h3>

Você deve ter o Anaconda Python 3.7 instalado. Se não tiver, basta fazer o download do instalador nesse <a href="https://www.anaconda.com/distribution/">link</a>. A instalação é bem simples bastando clicar “Next” várias vezes.

Depois, basta procurar por “Anaconda Navigator” e, após abrí-lo, clicar em “Jupyter Notebook”. Como na imagem abaixo:

<img src="anaconda.jpeg">

Ao clicar em “Jupyter notebook” a interface deste programa se abrirá no seu navegador de internet padrão. Daí então é só clicar em “New” e escolher Python 3, como mostra a figura abaixo:

<img src="jupyter.jpeg">

Abrirá uma nova aba no seu navegador, como na figura abaixo, daí, basta digitar comandos e apertar “run”, indicado pelo quadrado vermelho na imagem. Neste exemplo, pedimos para o computador imprimir “Hello, world!”

<img src="notebook.jpeg">

Estamos prontos para começar!

<h3>1. Strings</h3>

A palavra "string" significa <i>sequência de caracteres</i>. Um caracter é qualquer símbolo gráfico usado para compor textos, por exemplo: !@#$\%¨&*()_+012ABCabc

Uma string em Python é reconhecida quando digitamos uma sequência de caracteres entre aspas duplas. Por exemplo: "Hello, world!"

É possível, também, utilizar aspas simples: 'Hello, world!'

Os caracteres "quebra de linha" e "tabulação" são indicados respectivaemente por "\n" e "\t".

In [1]:
"Hello, world!"

In [2]:
'Hello, world!'

In [3]:
"\tHello,\n\t\tworld!"

<h3>2. Variáveis</h3>

Frequentemente, quando estamos programando, temos a necessidade de armazenar objetos (por exemplo, strings) em variáveis. Para fazê-lo em Python usamos um identificador, seguido do sinal de atribuição, seguido do objeto que queremos armazenar. Por exemplo, para armazernar a string "Hello, world!" na variável x, executamos o seguinte código:

In [4]:
x = "Hello, world!"

Um identificador não pode começar com números, nem conter caracteres especiais como espaços e tabulações. É comum usarmos underline (travessão), números no final do identificador e letras do nosso alfabeto, podendo ser maiúsculas e minúsculas. Por exemplo:

In [5]:
saudacoesPessoal = "Hello, world!"

O identificador da variável acima é <i>saudacoesPessoal</i>. A variável armazena a string "Hello, world!"

<h3>3. Built-in Functions</h3>

Built-in functions são funções prontas da linguagem Python. Vejamos, por exemplo, a built-in function <i>len</i>. Essa função conta quantos iteráveis tem num iterável. Podemos pensar num iterável como sendo um objeto que possamos separar suas partes. Por exemplo, podemos separar os caracteres de uma string. Vejamos como utilizar a função <i>len</i> para contar quanto caracteres possui a string "Hello, world!" 

In [6]:
len("Hello, world!")

Legal! O número total de caracteres é 13. Observe o quanto é fácil contar caracteres com Python sem ter que contar um por um.

Devemos passar o iterável entre parênteses. É possível passar uma variável como parâmetro para uma built-in function como no exemplo a seguir:

In [7]:
saudacoesPessoal = "Hello, world!"
len(saudacoesPessoal)

Outra built-in function muito utilizada é <i>print</i>. Essa função imprime o objeto.

In [8]:
saudacoesPessoal = "Hello, world!"
print(saudacoesPessoal)

In [9]:
saudacoesPessoal = "\tHello,\n\t\tworld!"
print(saudacoesPessoal)

<h3>4. Tipos de variáveis</h3>

Para saber qual o tipo de uma variável, basta utilizar a built-in function <i>type</i>. Vejamos o que <i>type</i> retorna ao ser aplicada numa string:

In [10]:
type("Hello, world!")

Como já vimos, é possível aplicar uma built-in function numa variável. Aplicando <i>type</i> numa variável, descobriremos qual o tipo dela.

In [11]:
x = "Aprendendo Python!"
type(x)

Para inserir comentários num código, usamos #. Linhas com comentários não são executadas pelo interpretador Python:

In [12]:
print("Antes")
# print("este é um comentário")
print("Depois")

A seguir veremos outros tipos de variáveis em Python. Os códigos serão comentados para compreendermos melhor que tipo de variável estamos apresentando. Primeiramente, as variáveis numéricas:

In [13]:
# n é um variável do tipo inteiro
n = 8
type(n)

In [14]:
# pi é uma variável do tipo float
pi = 3.1415
type(pi)

Agora, variáveis booleanas:

In [15]:
# s1 é uma variável do tipo booleana
s1 = True
type(s1)

In [16]:
# s2 é uma variável do tipo booleana
s2 = False
type(s2)

Sequências ordenadas de objetos Python:

In [17]:
# L é uma variável do tipo lista
# uma lista é uma sequência ordenada de objetos
L = [1, 2, 2.5, True]
type(L)

In [18]:
# T é uma variável do tipo tupla
# uma tupla também é uma sequência ordenada de objetos
T = (1, 2, 2.5, True)
type(T)

Por fim, dicionários:

In [19]:
# d é uma variável do tipo dicionário
d = {
    "alunos": ["Bia", "Bob", "Ted"],
    "notas": [9.8, 8.9, 9.3],
    "escola": "X-MG"
}
type(d)

<h3>5. Descobrindo e usando métodos</h3>

Todo objeto tem seus métodos. A built-in function <i>dir</i> apresenta uma lista desses métodos. Existem métodos privados e públicos. É uma boa prática usar apenas aqueles métodos que são públicos. Para saber quais são eles, procure por aqueles que não começam com underline. Vejamos, por exemplo, quais são os métodos de um objeto do tipo inteiro.

In [20]:
n = 5
dir(n)

Há apenas 8 métodos públicos: bit_length, conjugate, denominator, from_bytes, imag, numerator, real e to_bytes.

Ao consultar os métodos de um objeto do tipo lista, notamos um método chamado <i>count</i>. Para saber como usar o método, podemos utilizar a built-in function <i>help</i>.

In [21]:
L = [1, 1, 2, 3, 2, 3, 2, 4, 5, 5]
help(L.count)

A ajuda fala que o método <i>count</i> precisa de um <i>value</i>. Ao passar um valor para o método, este retorna o número de ocorrências daquele valor na lista. Vejamos na prática, contaremos quantos inteiros <i>2</i> temos na lista <i>L</i>.

In [22]:
L.count(2)

O inteiro <i>2</i> passado para o método <i>count</i> é chamado de parâmetro do método. Alguns métodos não possuem parâmetros. Por exemplo, o método <i>upper</i> de strings transforma a string deixando todas as letras maiúsculas.

In [23]:
saudacoes_antes = "Hello, world!"
saudacoes_antes.upper()

'HELLO, WORLD!'

Observe o quanto é fácil passar todo um texto enorme para maiúsculo sem ter que digitar tudo novamente.

É preciso também se atentar à sintaxe para utilização de métodos. Começa com a variável, seguida de um ponto, seguida do método, seguido de parênteses. Dentro dos parênteses são passados, se houver, os parâmetros. Essa sintaxe é necessária para que o interpretador Python entenda o que estamos pedindo para ele executar.

<h3>6. Operando objetos</h3>

Da mesma forma que operamos números inteiros, podemos operar objetos em Python. Por exemplo, podemos somar dois objetos do tipo inteiro utilizando o sinal de soma +:

In [24]:
n = 3
m = 4
total = n + m
print(total)

7


A variável <i>total</i> é do tipo inteiro. Mas, não necessariamente uma operação retorna o mesmo tipo de objeto daqueles que foram operados. Por exemplo, na divisão de dois inteiros, o objeto retornado é do tipo float.

In [25]:
n = 3
m = 4
total = 3/4
print(total)
print(type(total))

0.75
<class 'float'>


Ao operar strings, elas são concatenadas:

In [26]:
n = "Hello,"
m = " world!"
total = n + m
print(total)

Hello, world!


O mesmo acontece com listas e tuplas:

In [27]:
n = [1,2,4]
m = [5,7,9]
total = n + m
print(total)

[1, 2, 4, 5, 7, 9]


Além dos operadores aritméticos, temos os operadores lógicos. Novamente, os códigos a seguir serão comentados:

In [28]:
# operador maior
5 > 7

False

In [29]:
# operador menor ou igual
5 >= 7

False

In [30]:
# operador de igualdade
5 == 7

False

In [31]:
# operador de desigualdade
5 != 7

True

In [32]:
# operador de pertinência
5 in [1,2,4,6,7]

False

In [33]:
# operador de pertinência
6 in [1,2,4,6,7]

True

<h3>7. Fatiando objetos</h3>

Objetos iteráveis podem ser fatiados. Isso quer dizer que podemos acessar partes destes objetos. Considere a variável do tipo string a seguir:

In [34]:
name = "skywalker"

Para acessar partes da string acima, utilizaremos os índices desta. Os índices começam em 0. É possível contar de trás para frente, sendo que o último caractere tem o índice -1.

<img src="slicing.png" width="400px">

Vejamos alguns exemplos utilizando strings:

In [35]:
# a primeira letra
name[0]

's'

In [36]:
# a segunda letra
name[1]

'k'

In [37]:
# a última letra
name[-1]

'r'

In [38]:
# a penúltima letra
name[-2]

'e'

In [39]:
# do começo até a terceira
name[:3]

'sky'

In [40]:
# do começo até a penúltima
name[:-2]

'skywalk'

In [41]:
# da quarta até a última
name[3:]

'walker'

In [42]:
# da quarta até a ante-penúltima
name[3:-2]

'walk'

In [43]:
# da segunda até a penúltima de 2 em 2
name[1:-1:2]

'kwle'

In [44]:
# da penúltima até a segunda de 2 em 2
name[-2:0:-2]

'elwk'

In [45]:
# do começo até a penúltima de 2 em 2
name[:-1:2]

'syak'

In [46]:
# do começo até a última de 3 em 3
name[::3]

'swk'

In [47]:
# da úlima até a primeira de um em 1
name[::-1]

'reklawyks'

O mesmo processo de fatiamento pode ser aplicado em qualquer tipo de iterável. Por exemplo, em objetos do tipo lista ou do tipo tupla.

<h3>8. If... Else...</h3>

As palavras <i>if</i> e <i>else</i> são palavras reservadas da linguagem Python. Elas são utilizadas para controlar o fluxo de execução de um código através de condições. A palavra <i>if</i> significa "se" e a palavra <i>else</i> significa "senão":

In [48]:
idade = 17

if idade >= 18:
    print("Pode entrar!")
else:
    print("Não pode entrar!")

Não pode entrar!


No exemplo acima, vimos que a linha 4 não foi executada. De fato, uma vez que a condição <i>idade >= 18</i> é falsa, códigos após uma linha contendo <i>if</i> e identados não serão executados. Por identado, considere códigos que iniciam por 4 espaços. Observe que há quatro espaços antes do código na linha 4. Os 4 espaços indicam o que deve ser executado se a condição for verdadeira. Da mesma forma há 4 espaços no início da linha 6. Neste segundo caso, os 4 espaços indicam o que deve ser executado se a condição for falsa. Vejamos outros exemplos.

In [49]:
idade = 21

if idade >= 18:
    print("Você é de maior.")
    print("Pode entrar")
else:
    print("Você é de menor.")
    print("Não pode entar.")
print("Próximo!")

Você é de maior.
Pode entrar
Próximo!


No exemplo acima, a condição <i>idade >= 18</i> é verdadeira e, por isso, as linhas 4 e 5 foram executadas. Se fosse falsa, seriam as linhas 7 e 8 as executadas. Como a linha 9 não está identada (digitada após 4 espaços), ela é executada de toda forma.

<h3>9. Loop for</h3>

Outra palavra reservada na linguagem Python é <i>for</i>. Ela serve para que em cada iteração, acessemos valores de um iterável. Por exemplo, podemos acessar em cada iteração as letras de uma string ou os elementos de uma lista.

In [50]:
for letra in "Python":
    print(letra)

P
y
t
h
o
n


No exemplo acima, a variável <i>letra</i> assume uma das letras do objeto "Python" a cada iteração. Assim como no if... else..., a cada iteração são executadas apenas as linhas que tiverem identadas (após 4 espaços).

In [51]:
for letra in "Python":
    print("Entendi!")
print("Vamos dominar o mundo!")

Entendi!
Entendi!
Entendi!
Entendi!
Entendi!
Entendi!
Vamos dominar o mundo!


É possível colocar condicionais dentro de loops, loops dentro de condicionais, condicionais dentro de condicionais e loops dentro de loops. Vejamos um exemplo de como imprimir apenas os números maiores que 5 de uma lista.

In [52]:
for number in [5,12,2,56,-20,21,3,4,7,8]:
    if number > 5:
        print(number)

12
56
21
7
8


<h3>10. Funções</h3>

Apesar da linguagem Python ter várias built-in functions, às vezes é necessário criamos nossas próprias funções. Para facilitar, pense em função como algo que possui três componentes: entrada, lógica que transforma a entrada em saída e a saída. A palavra Python reservada para criar funções é <i>def</i>. Como exemplo, veremos como fazer uma função que retorna como saída o quadrado da entrada: 

In [53]:
def func(entrada):
    saida = entrada * entrada # logica
    return saida 

O nome da função acima, escolhido por nós, é <i>func</i>. Podemos usá-la como usamos uma built-in function:

In [54]:
x = 9
resultado = func(x)
print(resultado)

81


<h3>11. Bibliotecas</h3>

A comunidade Python é gigante e muitos programadores dessa comunidade criam bibliotecas com outras funções úteis e disponibilizam essas bibliotecas gratuitamente em repositórios on-line.

Ao instalar o Anaconda, já foram instaladas diversas bibliotecas úteis como, por exemplo, a biblioteca <i>numpy</i>, utilizada para trabalhar com matrizes ou tabelas. Para importar uma biblioteca, utilizamos a palavra reservada <i>import</i>.

In [55]:
import numpy

Dentro de uma bibliotecas temos mais objetos e mais funções para usarmos. Um objeto muito utilizado da biblioteca numpy é o <i>ndarray</i> para fazer matrizes.

In [56]:
A = numpy.array([[1,2,5],[0,-3,-1],[0,2,4],[5,6,8]])
type(A)

numpy.ndarray

Algumas built-in functions são adaptadas para esses novos objetos e, em alguns casos, funcionam perfeitamente, como por exemplo a built-in function print:

In [57]:
print(A)

[[ 1  2  5]
 [ 0 -3 -1]
 [ 0  2  4]
 [ 5  6  8]]


Esses novos objetos funcionam como qualquer outro objeto Python. Logo têm seus próprios métodos privados e públicos. Por exemplo, o método <i>reshape</i> muda as dimensões de um objeto do tipo ndarray:

In [58]:
# transformando A em uma matriz com
# 2 linhas e 6 colunas
A.reshape(2,6)

array([[ 1,  2,  5,  0, -3, -1],
       [ 0,  2,  4,  5,  6,  8]])

<h3>Conclusão</h3>

É isso aí pessoal, essa é apenas uma visão geral para quem está começando. Agora é só praticar.

Algumas perguntas devem ter surgido, por exemplo:

- Qual a diferença entre tupla e lista?
- Quando uso dicionários? Dicionários são Json?
- Uma função pode não retornar nada?
- Posso criar meus próprios objetos com meus próprios métodos?
- Porque o Jupyter Notebook mostra o objeto mesmo sem a built-in function <i>print</i>?
- Como faço e como uso conjuntos em Python?
- Como leio arquivos de textos ou planilhas?
- Como coleto dados de páginas de internet de forma automatizada?
- É possível fazer um chatbot em Python?
- É possível ler e manipular imagens em Python?
- Como faço jogos em Python?
- Como crio minhas próprias bibliotecas?
- Como usar Python para fazer websites?
- Como usar Python para trabalhar com inteligência artificial?
- Python é rápido como as outras linguagens? Tem como acelerar?


Nós da comunidade <b>UraPython</b> temos por missão levar todo esse conhecimento a quem quer que seja. Queremos com isso, dar as mesmas oportunidades às pessoas, para que estas possam ter uma vida digna, confortável e feliz. Além disso, queremos oferecer as habilidades essenciais para que as pessoas se adaptem continuamente às tecnologias emergentes na velocidade que o futuro exige.

Até a próxima!